# Generated by Django 2.2.6 on 2019-12-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20191202_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id', 'full_name']},
        ),
    ]
